development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: **ruby**
  pool: 5
  username: **root**
  password: ****
  **socket: /opt/local/var/run/mysql5/mysqld.sock**
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: **ruby**
  pool: 5
  username: **root**
  password: ****
  socket: **/opt/local/var/run/mysql5/mysqld.sock**

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: **ruby**
  pool: 5
  username: **root**
  password: ****
  socket: **/opt/local/var/run/mysql5/mysqld.sock**
